name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run lint
        run: ./gradlew lint

      - name: Upload lint report app
        uses: actions/upload-artifact@v2
        with:
          name: lint_report_app
          path: app/build/reports/tests/

      - name: Upload lint report module
        uses: actions/upload-artifact@v2
        with:
          name: lint_report_module
          path: ceprace/build/reports/tests/

  unit-test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: ./gradlew test

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Upload test report app
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report_app
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Upload test report module
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report_module
          path: ceprace/build/reports/tests/testDebugUnitTest/