name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy to JitPack
        uses: "ihciah/action-jitpack@v1.2.0"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ needs.release.outputs.version }}
