name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Create tag
        uses: actions-ecosystem/action-create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy to JitPack
        uses: "ihciah/action-jitpack@v1.2.0"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ needs.release.outputs.version }}
